config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'filter/index' => 'filter#index', as: 'filter_index_get'
  post 'filter/index' => 'filter#index', as: 'filter_index'
  get 'filter/delete_selected' => 'filter#delete_selected', as: 'filter_delete'
  post 'filter/handle_post' => 'filter#handle_post', as: 'handle_post'
  
  get '/' => 'goods#index', as: 'goods_index_get' 
  post '/' => 'goods#index', as: 'goods_index'
  root to: 'goods#index'
  resources :users, only: %i[show update]
  get '/user/good_show' => 'users#good_show'
  get '/user/my_cart' => 'users#my_cart'
  get '/user/my_goods' => 'users#my_goods'
  get '/user/sold_goods' => 'users#sold_goods'

  resources :goods, only: %i[new create show index destroy]
  # get '/good/show' => 'goods#show'
  post '/goods/new' => 'goods#new'
  get '/good/edit' => 'goods#edit'
  post '/good/edit' => 'goods#edit'
  patch '/good/update' => 'goods#update'
  post '/good/update' => 'goods#update'
  get '/good/back_from_bought' => 'goods#back_from_bought'
  get '/good/delete_num' => 'goods#delete_num'
  get '/for_u' => 'goods#for_u'
  get '/food' => 'goods#food'
  get '/drink' => 'goods#drink'
  get '/else' => 'goods#else'
  # get '/search' => 'goods#search'
  get :autocomplete, controller: :goods, format: 'json'
  delete '/goods/delete' => 'goods#delete'
  post '/goods/delete' => 'goods#delete'
  post '/goods/delete_all' => 'goods#delete_all'
  get '/autocomplete/', to: 'goods#autocomplete'
  get '/search/', to: 'goods#search'
  get '/index_search/', to: 'goods#index_search'

  post '/goods/:id', to: 'goods#view'
  get '/tags/:id', to: 'goods#show_goods_with_tag'

  # post '/goods/new' => 'goods#create'

  get '/purchases/to_cart' => 'purchases#to_cart'
  post '/purchases/to_cart' => 'purchases#to_cart'
  get '/purchases/back_from_cart' => 'purchases#back_from_cart', as: "back_from_cart"
  get '/purchases/delete' => 'purchases#delete'

  get '/product/choose' => 'products#choose'
  post '/product/new_from_product' => 'products#new_from_product'
  get '/product/new_from_product' => 'products#new_from_product'
  post '/product/create_from_product' => 'products#create_from_product'
  get 'product/search'=> 'products#search'

  get '/conversations/search/', to: 'conversations#search'
  get '/conversations/view', to: 'conversations#view'

  resources :conversations do
    resources :messages
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:authsch]

  def self.from_omniauth(access_token)
    data = access_token.extra.raw_info
    user = User.find_by(email: data['mail'])

    # Uncomment the section below if you want users to be created if they don't exist
    user ||= User.create(username: data['displayName'],
                         email: data['mail'],
                         password: Devise.friendly_token[0, 20])
    user
  end

  has_many :goods
  has_many :intrests
  has_many :tags, through: :intrests

  acts_as_messageable

  def name
    username.to_s
  end

  def mailboxer_email(_object)
    nil
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def authsch
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Auth.sch'
      sign_in_and_redirect @user, event: :authentication
    else
      redirect_to root_path, alert: @user.errors.full_messages.join('\n')
    end
  end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :check_good_id, only: [:good_show]
  include ProductsHelper

  def good_show
    @good = Good.with_deleted.find(params[:id])
  end

  def my_cart
    @purchases = Purchase.all.order(created_at: :desc)
  end

  def my_goods
    @goods = Good.with_attached_photo.without_deleted.all.order(updated_at: :desc)
    @products = get_proucts_for_goods(@goods)
  end

  def sold_goods
    @purchases = Purchase.all.order(created_at: :desc)
  end

  def show; end

  def update
    if params[:new_room]
      good_number = Good.where(seller_id: current_user.id).size
      level_num_update(-good_number, current_user.roomnumber)
      current_user.update_attributes(roomnumber: params[:new_room])
      level_num_update(good_number, current_user.roomnumber)
    end
    if !params[:new_description].nil?
      current_user.update_attributes(description: params[:new_description])
    end
    if params[:want_email] == 'Igen'
      current_user.update_attributes(want_email: true)
    else
      current_user.update_attributes(want_email: false)
    end
    redirect_to user_path
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/good_show.html.erb
<div class="uk-child-width-1-2 uk-flex-center" uk-grid>
  <div>
    <div class="uk-background-muted" uk-grid>
      <div class="uk-width-1-3@m uk-padding">
        <%=image_tag get_image(@good)%>
      </div>
      <div class="uk-width-2-3@m">
        <p>
          <strong>Név:</strong>
          <%= @good.name %>
        </p>

        <p>
          <strong>Ár/db:</strong>
          <%= @good.price %> Ft
        </p>

        <p>
          <strong>Darabszám:</strong>
          <% if params[:purchase_id].nil? %>
            <%= @good.number %>
          <% else %>
            <%= Purchase.find(params[:purchase_id]).number %>
          <% end %>
        </p>

        <% unless params[:purchase_id].nil? %>
          <p>
            <strong>Összesen fizetendő:</strong>
            <%= Purchase.find(params[:purchase_id]).number * @good.price %> Ft
          </p>
        <% end %>

        <p>
          <% if @good.seller_id != current_user.id %>
            <strong>Eladó:</strong>
            <% seller = User.find_by_id(@good.seller_id) %>
              <span class = "uk-visible@l"> <%= link_to seller.username, conversations_path(sender_id: current_user.id, receiver_id: seller.id), method: :post  %></span>
              <span class = "uk-hidden@l"> <%= link_to seller.username, conversations_path(sender_id: current_user.id, receiver_id: seller.id, mobile: "middle"), method: :post  %></span>
          <% elsif @good.seller_id == current_user.id && !params[:purchase_id].nil? %>
            <strong>Vevő:</strong>
            <% purchase = Purchase.find(params[:purchase_id]) %>
            <% buyer = User.find_by_id(purchase.buyer_id) %>
            <span class = "uk-visible@l"> <%= link_to buyer.username, conversations_path(sender_id: current_user.id, receiver_id: buyer.id), method: :post  %> </span>
            <span class = "uk-hidden@l"> <%= link_to buyer.username, conversations_path(sender_id: current_user.id, receiver_id: buyer.id, mobile: "middle"), method: :post  %> </span>
          <% end %>
        </p>

        <%=render partial:"goods/tags", object:@good.tags%>

        <p>
          <strong>Leírás:</strong>
          <%= @good.description %>
        </p>

        <% if @good.seller_id == current_user.id && params[:purchase_id].nil? %>
          <a href="#modal-center" uk-toggle>Törlés</a>
          <p><%= link_to 'Szerkesztés', {action: 'edit', controller: 'goods', id: @good.id}%></p>
        <% end %>
        <% unless params[:purchase_id].nil? %>
          <% purchase = Purchase.find(params[:purchase_id]) %>
          <% if purchase.buyer_id == current_user.id %>           
            <p>
              <% uzenet = "Tényleg törölni akarod a rendelést?"%>
              <%=link_to "Eldobás", {action: 'back_from_cart', controller: 'purchases', id: purchase.id}, data: {confirm: uzenet} %>
            </p>
          <% else %> 
            <p>
              <% uzenet = "Valóban kifezette " + User.find_by_id(purchase.buyer_id).username + " a vásárlást?"%>
              <%=link_to "Kifizetve", { action: 'delete', controller: 'purchases', id: purchase.id }, data: {confirm: uzenet} %>
            </p>
          <% end %>
        <% end %>
      </div>
    </div>   
  </div>
</div>

<div id="modal-center" class="uk-flex-top" uk-modal>
    <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">
        <button class="uk-modal-close-default" type="button" uk-close></button>
        <% new_good = Good.new %>
        <div align = "center">
          <%= form_for new_good, :url => url_for(action: 'delete', controller: 'goods'), class: "uk-form-horizontal uk-margin-large" do |f| %>
            <%= f.select :number, options_for_select(0..@good.number)%>   
            <%= hidden_field_tag(:id, @good.id)%>
            <%= f.submit "Törlés" %>
          <% end %>
        </div>
    </div>
</div>

app/views/users/my_cart.html.erb
<div class="uk-child-width-1-2@l  uk-flex-center " uk-grid>    
        <div class="uk-align-center uk-card uk-card-secondary uk-card-body" uk-sticky="offset: 80; bottom: #top"
        style="z-index: 1">
            <h1 class="uk-text-center uk-text-bold" style = "color: #8e8e8e">Kosaram</h1>
            <% osszeg = 0 %>
            <% if !@purchases.nil? %>
                <% @purchases.each do |p| %>
                    <% if p.buyer_id == current_user.id %>
                        <% good = Good.with_deleted.find(p.good_id) %>
                      
                    <div> <% osszeg += p.number*good.price%></div>
                    <% end %>
                <% end %>
            <% end %>

            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-expand" uk-leader="fill: -">Összesen:</div>
                <div><%= osszeg%> Ft</div>
            </div>
        </div>
</div>

<div class="uk-child-width-1-2@l  uk-flex-center" uk-grid>    
       <ul class="uk-list uk-list-divider">
             <% @purchases.each do |p| %>
                <% if p.buyer_id == current_user.id%>
                <% good = Good.with_deleted.find(p.good_id) %>
                    <li>                                          
                       <table style="width:100%">
                            <tr>
                                <th style="uk-preserve-width,width:20%" rowspan="3">
                                        <% if good.photo.attached? %>
                                            <%= link_to action: 'good_show', id: good.id, purchase_id: p.id do %>
                                                <%= image_tag(good.photo) %>
                                            <% end %>
                                        <% else %>
                                            <% product = Product.find_by_id(good.product_id) %>
                                            <% if product.photo.attached? %>
                                                <%= link_to action: 'good_show', id: good.id, purchase_id: p.id do %>
                                                    <%= image_tag(product.photo) %>
                                                <% end %>
                                            <% end %> 
                                        <% end %>
                                        </th>
                                <th style="width:70%">
                                   <%= link_to good.name, {action: 'good_show', id: good.id, purchase_id: p.id}, class: "uk-link-reset" %>
                                </th>
                                <th style="width:10%">
                                    <div align="center">
                                    <% uzenet = "Tényleg törölni akarod a rendelést?"%>                                      
                                        <%= link_to back_from_cart_path(id: p.id), data: {confirm: uzenet} do %> <span uk-icon="icon: trash" uk-tooltip="title: Rendelés törlése; pos: bottom"></span><%end%> </div>
                                    </div>
                                </th>
                            </tr>
                            <tr>
                                <td rowspan="2"><div> Mennyiség: <%= p.number %> db</div></td>
                                <td rowspan="2"><div align = 'center'> <%= good.price*p.number %> Ft </div></td>
                            </tr>
                            <tr>
                            </tr>
                        </table>
                                            
                    </li>
                <%end%>
            <%end%>
       </ul>
</div>

app/views/users/my_goods.html.erb
<h1 class = "page-name-backgound top-100px"> Termékeim </h1>
<h1 class = "page-name top-100px"> Termékeim </h1>
    <% has_goods = false %>
    <div style = "padding-top: 150px;" class="uk-grid-small" uk-grid>
    <% @goods.each do |g| %>
      <% if g.seller_id == current_user.id%>
        <% has_goods = true %>
        <div class="uk-width-1-4@m">  
            <div class="uk-card-small uk-card-hover uk-card uk-card-default ">
                <div class="uk-card-header">
                    <div class="uk-grid-small uk-flex-middle" uk-grid>
                        <div class="uk-width-auto">
                            <%= link_to action: 'good_show', id: g.id do %>
                                <%= image_tag get_image(g,"list") %>
                            <% end %>
                        </div>
                        <div class="uk-width-expand">
                            <h3 class="uk-card-title uk-margin-remove-bottom">
                                <%= link_to g.name, {action: 'good_show', id: g.id}, class: "uk-link-reset" %>
                            </h3>
                            <p class="uk-text-meta uk-margin-remove-top"><time datetime="2016-04-01">
                                <%= g.updated_at.strftime("%Y-%m-%d, %H:%M") %>
                            </time></p>
                        </div>
                    </div>
                </div>
                <div class="uk-card-body uk-padding-remove-bottom">
                    <div> Ár: <%= g.price %> Ft/db &nbsp;&nbsp;  Mennyiség: <%= g.number %> db</div>
                </div>
                <div class="uk-card-footer">                    
                    <div align = 'center'>
                        <%= link_to action: 'edit', controller: 'goods', id: g.id do %> <span uk-icon="icon: file-edit" uk-tooltip="title: Szerkesztés; pos: bottom"></span><%end%>
                        <% uzenet = "Biztos kitörölsz " + g.number.to_s + " db terméket?" %>
                        <%= link_to g, method: :delete, remote: true, data: {confirm: uzenet} do %> <span uk-icon="icon: trash" uk-tooltip="title: Összes törlése; pos: bottom"></span><%end%>
                    </div>
                </div>
            </div>
        </div>
      <% end %>  
    <% end %>   
</div>
<% if has_goods == false %>   
    <h2 class = "page-name-backgound top-300px"> Jelenleg nem árulsz semmit </h2>
    <h2 class = "page-name top-300px"> Jelenleg nem árulsz semmit </h2>
<% end %>

app/views/users/show.html.erb
<div class="uk-flex uk-flex-center">
   <div class="uk-card uk-card-body uk-card-default	">

    <h1> <%= current_user.name %> </h1>

    <%= form_with url: user_path, method: :patch do |form| %>
      <% if current_user.roomnumber.nil? %>
        <h3 class = "uk-text-danger" > Szobaszám: </h3>
        <%= form.text_field :new_room, value: current_user.roomnumber, class: "danger-background" %>
      <% else %>
        <h3> Szobaszám: </h3>
        <%= form.text_field :new_room, value: current_user.roomnumber %>
      <% end %>
      <% options = ["Igen", "Nem"]%>
      <% if current_user.want_email %>
        <% which = "Igen" %>
      <% else %>
        <% which = "Nem" %>
      <% end %>
      <h3> E-mail értesítések a termékeid megrendeléséről/lemondásáról: </h3>
      <% options.each do |option| %>
        <% if which == option %>
          <%= form.radio_button :want_email, option, checked: true, class: "uk-radio" %>
          <%= label_tag(option) %>
        <% else %>
          <%= form.radio_button :want_email, option, checked: false, class: "uk-radio" %>
          <%= label_tag(option) %>
        <% end %>
      <% end %>
      <h3 align = 'left'> Leírás: </h3>
      <%= form.text_area :new_description, value: current_user.description, class: "uk-textarea" %>
      <button class="uk-button uk-button-primary">Mentés</button>
    <% end %>
  </div>
</div>
  
    

app/views/users/sold_goods.html.erb
<h1 class = "page-name-backgound top-100px"> Megrendelt termékeim </h1>
<h1 class = "page-name top-100px"> Megrendelt termékeim </h1>
    <% van = false %>
    <div class="uk-grid-small" uk-grid>
    <% @purchases.each do |p| %>
      <% good = Good.with_deleted.find(p.good_id) %>
        <%if good.seller_id == current_user.id%>
          <% van = true %>
        <div class="uk-width-1-4@m">  
            <div class="uk-card-small uk-card-hover uk-card uk-card-default ">
                <div class="uk-card-header">
                    <div class="uk-grid-small uk-flex-middle" uk-grid>
                        <div class="uk-width-auto">
                                <%= link_to action: 'good_show', purchase_id: p.id, id: good.id do %>
                                    <%= image_tag(get_image(good,"cart")) %>
                                <% end %>
                        </div>
                        <div class="uk-width-expand">
                            <h3 class="uk-card-title uk-margin-remove-bottom">
                                <%= link_to good.name, {action: 'good_show', purchase_id: p.id, id: good.id}, class: "uk-link-reset" %>
                            </h3>
                            <p class="uk-text-meta uk-margin-remove-top"><time datetime="2016-04-01">
                                <%= good.updated_at.strftime("%Y-%m-%d, %H:%M") %>
                            </time></p>
                        </div>
                    </div>
                </div>
                <div class="uk-card-body uk-padding-remove-bottom">
                    <% vevő = "Vevő: " + User.find_by_id(p.buyer_id).username %>                    
                    <div>Mennyiség: <%= p.number %> db</div>
                    <div>Összeg: <%= p.number*good.price %> Ft</div>
                    <%= link_to vevő, conversations_path(sender_id: current_user.id, 
                                                    receiver_id: p.buyer_id), method: :post %>
                </div>
                <div class="uk-card-footer">                    
                    <div align = 'center'>
                        <% uzenet = "Valóban kifezette " + User.find_by_id(p.buyer_id).username + " a vásárlást?"%>
                        <%=link_to "Kifizetve", { action: 'delete', controller: 'purchases', id: p.id }, data: {confirm: uzenet} %>
                    </div>
                </div>
            </div>
        </div>
      <% end %>  
    <% end %>
</div>
<% unless van %>
    <h2 class = "page-name-backgound top-300px"> Nincs megrendelt terméked </h2>
    <h2 class = "page-name top-300px"> Nincs megrendelt terméked </h2>
<% end %>