config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'filter/index' => 'filter#index', as: 'filter_index_get'
  post 'filter/index' => 'filter#index', as: 'filter_index'
  get 'filter/delete_selected' => 'filter#delete_selected', as: 'filter_delete'
  post 'filter/handle_post' => 'filter#handle_post', as: 'handle_post'
  
  get '/' => 'goods#index', as: 'goods_index_get' 
  post '/' => 'goods#index', as: 'goods_index'
  root to: 'goods#index'
  resources :users, only: %i[show update]
  get '/user/good_show' => 'users#good_show'
  get '/user/my_cart' => 'users#my_cart'
  get '/user/my_goods' => 'users#my_goods'
  get '/user/sold_goods' => 'users#sold_goods'

  resources :goods, only: %i[new create show index destroy]
  # get '/good/show' => 'goods#show'
  post '/goods/new' => 'goods#new'
  get '/good/edit' => 'goods#edit'
  post '/good/edit' => 'goods#edit'
  patch '/good/update' => 'goods#update'
  post '/good/update' => 'goods#update'
  get '/good/back_from_bought' => 'goods#back_from_bought'
  get '/good/delete_num' => 'goods#delete_num'
  get '/for_u' => 'goods#for_u'
  get '/food' => 'goods#food'
  get '/drink' => 'goods#drink'
  get '/else' => 'goods#else'
  # get '/search' => 'goods#search'
  get :autocomplete, controller: :goods, format: 'json'
  delete '/goods/delete' => 'goods#delete'
  post '/goods/delete' => 'goods#delete'
  post '/goods/delete_all' => 'goods#delete_all'
  get '/autocomplete/', to: 'goods#autocomplete'
  get '/search/', to: 'goods#search'
  get '/index_search/', to: 'goods#index_search'

  post '/goods/:id', to: 'goods#view'
  get '/tags/:id', to: 'goods#show_goods_with_tag'

  # post '/goods/new' => 'goods#create'

  get '/purchases/to_cart' => 'purchases#to_cart'
  post '/purchases/to_cart' => 'purchases#to_cart'
  get '/purchases/back_from_cart' => 'purchases#back_from_cart', as: "back_from_cart"
  get '/purchases/delete' => 'purchases#delete'

  get '/product/choose' => 'products#choose'
  post '/product/new_from_product' => 'products#new_from_product'
  get '/product/new_from_product' => 'products#new_from_product'
  post '/product/create_from_product' => 'products#create_from_product'
  get 'product/search'=> 'products#search'

  get '/conversations/search/', to: 'conversations#search'
  get '/conversations/view', to: 'conversations#view'

  resources :conversations do
    resources :messages
  end
end

app/models/good.rb
# frozen_string_literal: true

class Good < ApplicationRecord
  include ApplicationHelper

  acts_as_paranoid
  belongs_to :user, optional: true
  validates :name, presence: true
  validates_numericality_of :price, presence: true
  has_one_attached :photo
  has_and_belongs_to_many :tags

  after_save :set_filename


  def thumb
    photo.variant(resize: '300x300!').processed
  end

  def thumb_list
    photo.variant(resize: '320x320!').processed
  end

  def thumb_cart
    photo.variant(resize: '100x100!').processed
  end

  def floor
    seller = User.find_by_id(seller_id)
    seller.roomnumber ? seller.roomnumber / 100 : nil
  end
end

app/controllers/goods_controller.rb
# frozen_string_literal: true

class GoodsController < ApplicationController
  include ProductsHelper
  include GoodsHelper

  before_action :force_json, only: :autocomplete

  def index
    @index = true
    @goods = getSelectedGoods
    @products = Product.with_attached_photo.all
    @sellers = find_sellers_for_goods(@goods)

    @recommendtaions = Recommendations.new(current_user).get_recommendations_from(@goods) unless current_user.nil?
  end

  def getSelectedGoods
    goods = Good.with_attached_photo.all.order(name: :asc, created_at: :desc).includes(:tags)
    unless params[:post].blank? || params[:post][:category_id].blank?
      goods = goods.select { |g| g.category_id == params[:post][:category_id].to_i }
    end
    unless params[:scearched_prase].blank?
      goods = goods.select { |g| g.name.downcase.include?(params[:scearched_prase].downcase) }
    end
    goods
  end

  def show
    @good = Good.with_attached_photo.find(params[:id])
    @product = Product.with_attached_photo.find(params[:id])
    @user = User.find_by_id(@good.seller_id)
    @order = Good.new
    UserIntrests.new(current_user).add_good_tags(@good) unless current_user.nil?
  end

  def view
    unless current_user.nil?
      good = Good.with_attached_photo.find(params[:id])
      UserIntrests.new(current_user).add_good_tags(good) unless current_user.nil?
    end
  end

  def edit
    @good = Good.find_by_id(params[:id])
    @main_tags = Tag.where(category: true)
  end

  def update
    @good = Good.find_by_id(params[:id])

    if @good.update_attributes(good_params)
      tag_num_update(-1, @good.tags)
      add_good_tags_from_params(@good)
      tag_num_update(1, @good.tags)
      redirect_to controller: 'users', action: 'good_show', id: @good.id
    else
      @main_tags = Tag.where(category: true)
      render action: 'edit'
    end
  end

  def new
    @main_tags = Tag.where(category: true)
  end

  def create
    @product = Product.new(product_params)
    @product.save
    @good = Good.new(good_params)

    @good.seller_id = current_user.id
    @good.product_id = @product.id
    if @good.save
      level_num_update(1, current_user.roomnumber)
      add_good_tags_from_params(@good)
      tag_num_update(1, @good.tags)
      @product.tags = @good.tags
      @product.save
      redirect_to controller: 'users', action: 'good_show', id: @good.id
    else
      render action: 'new'
    end
  end

  def delete_num
    @good = Good.find_by_id(params[:id])
    @number = Good.new
  end

  def destroy
    @good = Good.find_by_id(params[:id])
    number = @good.number
    @good.update_attributes(number: 0)
    level_num_update(-1, current_user.roomnumber)
    tag_num_update(-1, @good.tags)
    @good.destroy
    flash[:notice] = number.to_s + ' terméket töröltél'
    redirect_to controller: 'users', action: 'my_goods', method: :get
  end

  def delete
    @good = Good.find(params[:id])
    if params[:good].nil?
      level_num_update(-1, current_user.roomnumber)
      tag_num_update(-1, @good.tags)
      @good.destroy
      redirect_to controller: 'users', action: 'my_goods'
    else
      number = params[:good][:number].to_f
      if @good.number > number
        new_num = @good.number - number
        @good.update_attributes(number: new_num)
        flash[:notice] = t(:good_deleted)
        redirect_to controller: 'users', action: 'good_show', id: @good.id, method: :get
      else
        tag_num_update(-1, @good.tags)
        level_num_update(-1, current_user.roomnumber)
        @good.destroy
        flash[:notice] = t(:good_deleted)
        redirect_to controller: 'users', action: 'my_goods', method: :get
      end
    end
  end

  def for_u
    @goods = Good.with_attached_photo.all
    @recommendtaions = get_recommendations(50) unless current_user.nil?
    @products = get_proucts_for_goods(@goods)
  end

  def search
    term = if params[:index_phrase].nil?
             params[:scearched_prase].downcase
           else
             params[:index_phrase].downcase
           end

    @tags = Tag.select { |tag| tag.name.include?(term) }
    @goods = Good.select { |good| good.name.downcase.include?(term) }

    respond_to do |format|
      format.html do
        @goods = Good.select { |good| good.name.downcase.include?(term) || !(@tags & good.tags).empty? }
      end
      format.json do
        @tags = @tags.take(3)
        @goods = @goods.take(3)
      end
    end
  end

  def index_search
    term = params[:index_phrase].downcase
    @tags = Tag.select { |tag| tag.name.include?(term) }
    @goods = Good.select { |good| good.name.downcase.include?(term) }

    respond_to do |format|
      format.html do
        @goods = Good.select { |good| good.name.downcase.include?(term) || !(@tags & good.tags).empty? }
      end
      format.json do
        @tags = @tags.take(3)
        @goods = @goods.take(3)
        render 'search.json'
      end
    end
  end

  def autocomplete
    tag_name = params[:q].downcase
    @tags = Tag.select { |tag| tag.name.include?(tag_name) }

    respond_to do |format|
      format.json
    end
  end

  def show_goods_with_tag
    @goods = Tag.find(params[:id]).goods
    @products = get_proucts_for_goods(@goods)
    @sellers = find_sellers_for_goods(@goods)
  end

  private

  def good_params
    params.require(:good).permit(:name, :price, :text, :description, :number, :category_id)
  end

  def product_params
    params.require(:good).permit(:name, :photo, :category_id)
  end

  def add_good_tags_to_user_intrests(good)
    good.tags.each do |tag|
      intrest_in_tag = current_user.intrests.find { |intrest| intrest.tag == tag }
      if intrest_in_tag.nil?
        new_intrest = current_user.intrests.create(rate: 1)
        new_intrest.tag = tag
        new_intrest.save
      else
        intrest_in_tag.rate += 1
        intrest_in_tag.save
      end
    end
  end

  def add_good_tags_from_params(good)
    return if good.nil?

    selected_tags = params[:selected_tags].split('#')
    selected_tags.unshift(params[:good][:main_tag]) unless params[:good][:main_tag].nil?
    tags = Tag.all
    selected_tags.each do |tag|
      if tags.any? { |t| t.name == tag }
        good.tags << tags.find { |t| t.name == tag }
      else
        new_tag = Tag.create(name: tag)
        good.tags << new_tag
      end
    end
  end

  def get_recommendations(recommendations_count, _recommendation_per_tag_number = 2)
    recommendations = []
    user_favourite_tags.each do |tag|
      recommendations_per_tag = @goods.select { |good| good.tags.include?(tag) && !recommendations.include?(good) }
      recommendations_per_tag = recommendations_per_tag.first(2)

      recommendations_count -= recommendations_per_tag.size
      recommendations_per_tag.each do |rec|
        recommendations.push(rec)
      end
    end
    recommendations_from_other = Good.limit(recommendations_count).select { |good| !good.tags.include?(user_favourite_tags) && !recommendations.include?(good) }
    recommendations_from_other.each do |rec|
      recommendations.push(rec)
    end
    recommendations
  end

  def user_favourite_tags
    top_intrests = current_user.intrests.order(rate: :desc).limit(3)
    favourite_tags = []
    top_intrests.each do |intrest|
      favourite_tags.push(intrest.tag)
    end
    favourite_tags
  end

  def total_intrest_rate_in_tag(tag)
    total_intrest_rate = 0

    User.all.each do |user|
      user_intrest = user.intrests.find { |intrest| intrest.tag == tag }
      total_intrest_rate += user_intrest.rate unless user_intrest.nil?
    end

    total_intrest_rate
  end

  def force_json
    request.format = :json
  end
end

app/helpers/goods_helper.rb
# frozen_string_literal: true

module GoodsHelper
  def get_image(item, format = 'default')
    formats = {
      'list' => '400x400!',
      'cart' => '100x100!'
    }

    image = nil
    if item.photo.attached?
      image = item.photo

    elsif item.instance_of? Good
      if !@products.nil? && @products.any? { |p| p.id == item.product_id }
        product = @products.find { |p| p.id == item.product_id }
        image = product.photo if product.photo.attached?
      else

        product = Product.find_by_id(item.product_id)
        image = product.photo if product.photo.attached?
      end
    end

    if image.nil?
      return "default#{formats[format]}.jpg" unless format == 'default'

      return 'default.jpg'
    else
      unless format == 'default'
        image = image.variant(resize: formats[format]).processed
      end
      return image
    end
  end

  def find_seller(id)
    @sellers.nil? ? User.find(id) : @sellers.find { |seller| seller.id == id }
  end

  def find_sellers_for_goods(goods)
    seller_ids = []
    goods.each do |good|
      seller_id = good.seller_id
      seller_ids.push(seller_id) unless seller_ids.include?(seller_id)
    end
    User.where(id: seller_ids)
  end

  def goods_floor_count(floor)
    Good.all.select{|g| g.floor == floor}.size
  end
end

app/views/goods/_filter.html.erb
<script>
    function addFloor(id = 0) {
        if (id != 0) {
            index = id.split("_");
            selected_floors=$("#selected_floors");
            let array;
            if ( selected_floors.val() == "") {
                selected_floors.val(index[0]);
            }
            else {
                array = selected_floors.val().split("#");
                if( !array.includes(index[0]) ) {
                    selected_floors.val(selected_floors.val() + "#" + index[0])
                }
                else {
                    for ( i = 0; i < array.length; i++ ) {
                        if ( array[i] == index[0] ) {
                            array.splice(i,1);
                        }
                    }
                    selected_floors.val("");
                    if (array[0] != null)
                        selected_floors.val(array[0]);
                    for ( i = 1; i < array.length; i++ ) {
                        selected_floors.val(selected_floors.val() + "#" + array[i])
                    }
                }
            }
        }
    }
    function addTag(id = 0) {
        if (id != 0) {
            var index = id.split("[yes]");
            selected_tags=$("#selected_tags");
            let array;
            if ( selected_tags.val() == "") {
                selected_tags.val(index[0]);
            }
            else {
                array = selected_tags.val().split("#");
                if( !array.includes(index[0]) ) {
                    selected_tags.val(selected_tags.val() + "#" + index[0])
                }
                else {
                    for ( i = 0; i < array.length; i++ ) {
                        if ( array[i] == index[0] ) {
                            array.splice(i,1);
                        }
                    }
                    selected_tags.val("");
                    if (array[0] != null)
                        selected_tags.val(array[0]);
                    for ( i = 1; i < array.length; i++ ) {
                        selected_tags.val(selected_tags.val() + "#" + array[i])
                    }
                }
            }
        }
    }
    function setFilters() {
        let array = <%= @selected_floors.inspect.html_safe %>
        for (i = 0; i < array.length; i++) {
            let id = array[i] + "_yes";
            if (document.getElementById(id) != null ) {
                document.getElementById(id).checked = true;
                addFloor(id);
            }
        }
    }
    function setFiltersTags() {
        let array = <%= @selected_tags.inspect.html_safe %>
        for (i = 0; i < array.length; i++) {
            let id = array[i];
            if (id != null) {
                document.getElementById(id).checked = true;
                addTag(id);
            }
        }
    }
</script>
<%= form_tag goods_index_get_path, method: :get do %>
    <h3 style = "display: inline;">Szürők</h3>
    <%= button_tag(type: "submit", class: "uk-align-right uk-button uk-button-primary uk-border-circle uk-padding-small uk-padding-remove-top uk-padding-remove-bottom") do %>
        <span uk-icon="icon: settings" uk-tooltip="title: Mehet!; pos: bottom" ></span>
    <% end %>    
    <% if @searched_phrase.nil? %>
       <% @searched_phrase = ""%>
    <% end %>
    <div class = "uk-padding-small uk-padding-remove-left uk-padding-remove-right uk-padding-remove-bottom"><%= text_field_tag :searched_phrase, @searched_phrase, class: "uk-input uk-border-pill uk-form-width-medium", placeholder: "Keresés" %></div>
    <h4> Elérhető szintek</h4>
    <% num = 0%>
    <% @levels.each do |l|%>
        <% num += 1%>
        <% if num <= 7 %>
          <div class="uk-margin-small uk-padding-small uk-padding-remove-bottom uk-padding-remove-top">
            <span class = "uk-text-emphasis"><%= l.number %></span>
            <span class = "uk-text-muted"><%= " (" + l.good_number.to_s + ")" %></span>
            <%= check_box l.number, "yes", onchange:"addFloor(this.id);", class: "uk-checkbox uk-border-circle" %>
        </div>
        <% else %>
          <div class="toggle-animation-queued uk-margin-small uk-padding-small uk-padding-remove-bottom uk-padding-remove-top" hidden>
            <span class = "uk-text-emphasis"><%= l.number %></span>
            <span class = "uk-text-muted"><%= " (" + l.good_number.to_s + ")" %></span>
            <%= check_box l.number, "yes", onchange:"addFloor(this.id);", class: "uk-checkbox uk-border-circle" %>
        </div>
        <% end %>
    <% end %>
    <% if num > 7 %>
        <button class="uk-margin-medium-left toggle-animation-queued uk-button uk-button-default uk-border-circle uk-padding-small uk-padding-remove-top uk-padding-remove-bottom " type="button" uk-toggle="target: .toggle-animation-queued;">
            <span uk-icon="chevron-down"></span>
        </button>
        <button class="uk-margin-medium-left toggle-animation-queued uk-button uk-button-default uk-border-circle uk-padding-small uk-padding-remove-top uk-padding-remove-bottom " type="button" uk-toggle="target: .toggle-animation-queued;" hidden>
            <span uk-icon="chevron-up"></span>
        </button>
    <% end %>
   
    <%= hidden_field_tag :selected_floors, ''  %>
    <hr>
    <h4 style = "display: inline;">Tagek</h4>
    <% if !@prev_tags_str.nil? && @prev_tags_str.count("a-zA-Z") > 0 %>
        <span class = "uk-align-right">
            <%= link_to 'Szűrés törlése', goods_index_get_path(prev_tags: "") %>
        </span>
    <% end %>
    <div class = "uk-padding-small"> <%= render partial: 'prev_tags_badges' %> </div>
    <% num = 0%>
    <% @tags.each do |t|%>
        <% num += 1%>
        <% if num <= 7 %>
        <div class="uk-margin-small uk-padding-small uk-padding-remove-bottom uk-padding-remove-top">
            <span class = "uk-text-emphasis"><%= t.name %></span>
            <span class = "uk-text-muted"><%= " (" + t.number.to_s + ")"%></span>
            <%= check_box t.name, "yes", id: t.name, onchange:"addTag(this.name);", class: "uk-checkbox uk-border-circle" %>
        </div>
        <% else %>
        <div class="toggle-animation-queued-2 uk-margin-small uk-padding-small uk-padding-remove-bottom uk-padding-remove-top" hidden>
            <span class = "uk-text-emphasis"><%= t.name %></span>
            <span class = "uk-text-muted"><%= " (" + t.number.to_s + ")"%></span>
            <%= check_box t.name, "yes", id: t.name, onchange:"addTag(this.name);", class: "uk-checkbox uk-border-circle" %>
        </div>
        <% end %>
    <% end %>
    <% if num > 7 %>
        <button class="uk-margin-medium-left toggle-animation-queued-2 uk-button uk-button-default uk-border-circle uk-padding-small uk-padding-remove-top uk-padding-remove-bottom " type="button" uk-toggle="target: .toggle-animation-queued-2;">
            <span uk-icon="chevron-down"></span>
        </button>
        <button class="uk-margin-medium-left toggle-animation-queued-2 uk-button uk-button-default uk-border-circle uk-padding-small uk-padding-remove-top uk-padding-remove-bottom " type="button" uk-toggle="target: .toggle-animation-queued-2;" hidden>
            <span uk-icon="chevron-up"></span>
        </button>
    <% end %>

    <%= hidden_field_tag :selected_tags, ''  %>
    <%= hidden_field_tag :prev_tags, @prev_tags_str  %>
    <%= hidden_field_tag :order_by, @order_by  %>
    <%= hidden_field_tag :order_direction, @order_direction  %> 
<% end %>
<% unless @selected_floors.nil? %>
    <%= javascript_tag "setFilters()" %>
<% end %>
<!--<% unless @selected_tags.nil? && @selected_tags != "" %>
    <%= javascript_tag "setFiltersTags()" %>
<% end %>
-->

app/views/goods/_for_u.html.erb
<% if !current_user.nil? && !@recommendtaions.blank? %>
  <h3><%= link_to 'Neked ajánlott', {action: 'for_u'} %></h3>
  <%=render partial:"slider", object:@recommendtaions%>
  <hr class="uk-divider-icon">
<% end %>

app/views/goods/_listelement.html.erb
<%= link_to good_path(listelement), class: "uk-link-reset modal-link", id:"link-#{listelement.id}", method: :post ,remote: :true do %>

  <div class="uk-card uk-card-default uk-card-hover uk-border-rounded" style="pointer-events: none;">
    <div class="uk-card-media-top">
      <%= image_tag get_image(listelement,"list"), class: "uk-border-rounded"%>
    </div>
    <div class="uk-card-body uk-padding-small">
      <span class="uk-badge" ><%= listelement.price%> Ft</span>
      <div> <%= listelement.name %> </div>
    </div>
  </div>
<%end%>

<div id="modal-<%=listelement.id%>" class="uk-flex-top" uk-modal>
    <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">

        <button class="uk-modal-close-default" type="button" uk-close></button>
       <%= render partial: "goods/modal",object: listelement %>         
    </div>
</div>

app/views/goods/_modal.html.erb
<div>
    <div class="" uk-grid>
        <div class="uk-width-1-3@m">
            <%=image_tag get_image(modal,"list")%>

            </div>
            <div class="uk-width-2-3@m">
            
                    <p>
                    <strong>Név:</strong>
                    <%= modal.name %>                    
                    </p>

                    <p>
                    <strong>Ár/db:</strong>
                    <%= modal.price %>
                    Ft
                    </p>

                    <p>
                    <strong>Darabszám:</strong>
                    <%= modal.number %>
                    </p>

                    <p>
                    <!--@sellers.select{|seller| seller.id==modal.seller_id}.first
                    <% seller = find_seller(modal.seller_id)%>-->
                    <% seller = User.find_by_id(modal.seller_id)%>
                    <% if current_user.nil? %>
                        <strong>Eladó:</strong> <%= seller.username %>
                    <% elsif current_user != seller %>
                        <strong>Eladó:</strong> 
                        <span class = "uk-visible@l"> <%= link_to seller.username, conversations_path(sender_id: current_user.id, receiver_id: seller.id), method: :post  %></span>
                        <span class = "uk-hidden@l"> <%= link_to seller.username, conversations_path(sender_id: current_user.id, receiver_id: seller.id, mobile: "middle"), method: :post  %></span>
                    <% else %>
                        <strong>saját termék</strong>
                    <% end %>
                    </p>
                    <div>
                        <%=render partial:"goods/tags", object:modal.tags%>
                    </div>

                    <p>
                    <strong>Leírás:</strong>
                    <%= modal.description %>
                    </p>
                    <%@order = Good.new%>
                    <% if current_user != seller && !current_user.nil? %>
                    <%= form_for @order, :url => url_for(action: 'to_cart', controller: 'purchases',
                                                        id: modal.id) do |f| %>
                        <div>
                        <%= f.label :Mennyiség %>:
                        <%= f.text_field :number,class:"uk-input uk-form-width-medium" %>
                        <%=f.submit "Kosárba" ,class:"uk-button uk-button-default " %>
                        </div>
                    <% end %>
                    <% end %>
            </div>
    </div>    
</div>

app/views/goods/_searchbar.html.erb
<div>
<%if @categories.nil?%>
  <% @categories= Category.all%>
  <%end%>
  <%= form_tag(filter_index_get_path, method: :get) do %>
      <%= collection_select(:post,:category_id, @categories, :id, :name,
      :include_blank => "Összes") %>
      <%= text_field_tag(:scearched_prase) %>
    <%= submit_tag("Keres") %>
  <% end %>
</div>

app/views/goods/_templateelement.html.erb
<div class="uk-text-center" width="500px" height="500px" >
        <div class="uk-inline-clip uk-transition-toggle" tabindex="0">
           <%= image_tag get_image(templateelement,"list")%>
            <div class="uk-transition-fade uk-position-cover  uk-overlay uk-overlay-default uk-flex uk-flex-center uk-flex-middle">
              <%if controller_name=="products"%>
                <%= link_to "Kiválaszt", product_new_from_product_path( :good => { :product_id =>templateelement.id }),:method=> :post,class: "uk-h1 uk-margin-remove" %> 
              <%else%>
                <%= link_to templateelement.name, url_for(templateelement), class: "uk-h1 uk-margin-remove" %>
              <%end%>
            </div>
        </div>
</div>

app/views/goods/index.html.erb
<script>
function encodeHTML(s) {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
}
document.addEventListener("turbolinks:load",function(){
    const index_input=$("#index_input");

    var options = {
        getValue: "name",
        template: {
		type: "custom",
		method: function(value, item) {
      if (item.price==undefined) {
        return item.name;
      }
			return `
        <div style='overflow: auto;'>
          <img style='float:right;' src='${item.image}'/>
          ${encodeHTML(item.name)}
          <br/>
          ${item.price} Ft
        </div>`;
		}
	
    
	},
        url: function(phrase){
          return "/index_search?index_phrase="+phrase
        },
        categories: [
            {   
                listLocation: "goods",
                header: "<strong>Termékek<strong>"
            }, 
            {   
                listLocation: "tags",
                header: "<strong>Cimke<strong>"           
             }
        ],

       
        list: {
          onChooseEvent: function(){

            var url=index_input.getSelectedItemData().url
            
            index_input.val("");
            Turbolinks.visit(url)            
           
          }
        }
      }

    index_input.easyAutocomplete(options);
});
</script>
<div class = "uk-position-center uk-width-1-2@m">
    <div id="main" class="uk-background-cover">
        <%= form_tag filter_index_get_path, method: :get, id: "index_form", class: "uk-search uk-search-default uk-search-navbar uk-align-center uk-search-large uk-background-muted uk-border-rounded"  do %>
            <input name="searched_phrase" id="index_input" class="uk-search-input uk-width-1" type="search" placeholder="Keresés...">
            
            <button id="index_search_button" type="submit" form="index_form" class="uk-search-icon-flip" uk-search-icon></button>
        <% end %>
    </div>
    <div align = "center" class = "uk-padding-large">
      <%= link_to filter_index_get_path, method: :post do %>
        <button class = "uk-box-shadow-large uk-border-circle uk-button uk-padding-remove " uk-tooltip="title: Összes termék; pos: bottom;">
          <span style = "padding: 5px;" uk-icon="icon: grid; ratio: 2;"></span>
        </button>
      <% end %>
    </div>
</div>

app/views/goods/show.html.erb
<div class="uk-child-width-1-2  uk-flex-center" uk-grid>
  <div>
    <div class="uk-background-muted" uk-grid>
      <div class="uk-width-1-3@m uk-padding">
        <%=image_tag get_image(@good)%>
      </div>
      <div class="uk-width-2-3@m">
        <p>
          <strong>Név:</strong>
          <%= @good.name %>
        </p>

        <p>
          <strong>Ár/db:</strong>
          <%= @good.price %> Ft
        </p>

        <p>
          <strong>Darabszám:</strong>
          <%= @good.number %>
        </p>

        <p>
          <% if current_user.nil? %>
            <strong>Eladó: </strong> <%= @user.username %>
          <% elsif current_user != @user || current_user.nil? %>
            <strong>Eladó: </strong> 
            <span class = "uk-visible@l"> <%= link_to @user.username, conversations_path(sender_id: current_user.id, receiver_id: @user.id), method: :post  %></span>
            <span class = "uk-hidden@l"> <%= link_to @user.username, conversations_path(sender_id: current_user.id, receiver_id: @user.id, mobile: "middle"), method: :post  %></span>
          <% else %>
            <strong>saját termék</strong>
          <% end %>
        </p>
  
          <%=render partial:"tags", object:@good.tags%>

        <p>
          <strong>Leírás:</strong>
          <%= @good.description %>
        </p>

        <% if current_user != @user && !current_user.nil? %>
          <%= form_for @order, :url => url_for(action: 'to_cart', controller: 'purchases',
          id: @good.id) do |f| %>
            <div>
              <%= f.label :Mennyiség %>:
              <%= f.text_field :number,class:"uk-input uk-form-width-medium" %>
              <%=f.submit "Kosárba" ,class:"uk-button uk-button-default " %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>   
  </div>
</div>