config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'filter/index' => 'filter#index', as: 'filter_index_get'
  post 'filter/index' => 'filter#index', as: 'filter_index'
  get 'filter/delete_selected' => 'filter#delete_selected', as: 'filter_delete'
  post 'filter/handle_post' => 'filter#handle_post', as: 'handle_post'
  
  get '/' => 'goods#index', as: 'goods_index_get' 
  post '/' => 'goods#index', as: 'goods_index'
  root to: 'goods#index'
  resources :users, only: %i[show update]
  get '/user/good_show' => 'users#good_show'
  get '/user/my_cart' => 'users#my_cart'
  get '/user/my_goods' => 'users#my_goods'
  get '/user/sold_goods' => 'users#sold_goods'

  resources :goods, only: %i[new create show index destroy]
  # get '/good/show' => 'goods#show'
  post '/goods/new' => 'goods#new'
  get '/good/edit' => 'goods#edit'
  post '/good/edit' => 'goods#edit'
  patch '/good/update' => 'goods#update'
  post '/good/update' => 'goods#update'
  get '/good/back_from_bought' => 'goods#back_from_bought'
  get '/good/delete_num' => 'goods#delete_num'
  get '/for_u' => 'goods#for_u'
  get '/food' => 'goods#food'
  get '/drink' => 'goods#drink'
  get '/else' => 'goods#else'
  # get '/search' => 'goods#search'
  get :autocomplete, controller: :goods, format: 'json'
  delete '/goods/delete' => 'goods#delete'
  post '/goods/delete' => 'goods#delete'
  post '/goods/delete_all' => 'goods#delete_all'
  get '/autocomplete/', to: 'goods#autocomplete'
  get '/search/', to: 'goods#search'
  get '/index_search/', to: 'goods#index_search'

  post '/goods/:id', to: 'goods#view'
  get '/tags/:id', to: 'goods#show_goods_with_tag'

  # post '/goods/new' => 'goods#create'

  get '/purchases/to_cart' => 'purchases#to_cart'
  post '/purchases/to_cart' => 'purchases#to_cart'
  get '/purchases/back_from_cart' => 'purchases#back_from_cart', as: "back_from_cart"
  get '/purchases/delete' => 'purchases#delete'

  get '/product/choose' => 'products#choose'
  post '/product/new_from_product' => 'products#new_from_product'
  get '/product/new_from_product' => 'products#new_from_product'
  post '/product/create_from_product' => 'products#create_from_product'
  get 'product/search'=> 'products#search'

  get '/conversations/search/', to: 'conversations#search'
  get '/conversations/view', to: 'conversations#view'

  resources :conversations do
    resources :messages
  end
end

app/views/layouts/_footer.html.erb
<%# <div class="ui inverted vertical footer segment">
  <div class="ui center aligned container">
    <div class="ui inverted section divider"></div>
    <a href="http://kir-dev.sch.bme.hu" target="_blank">
      <img class="ui centered mini image" src="/images/kirdev.png">
    </a>
    <div class="ui horizontal inverted small divided link list">
      <a class="item" href="https://www.facebook.com/schorpong/">
        <i class="icon facebook"></i>Schörpong
      </a>
      <a class="item" href="mailto:schorpong@sch.bme.hu">
        <i class="icon mail"></i>schorpong@sch.bme.hu
      </a>
    </div>
    <div class="ui inverted section"></div>
  </div>
</div> %>


    <div class="uk-background-primary uk-position-bottom">
      <h1 class="">Footer</h1>
    </div>
   

<div class="uk-background-primary uk-position-bottom">
  <div class="ui center aligned container">
    <div class="ui inverted section divider"></div>
    <a href="http://kir-dev.sch.bme.hu" target="_blank">
    <%=image_tag "kirdev.png"%>
    </a>
    <div class="ui horizontal inverted small divided link list">
      <a class="item" href="https://www.facebook.com/schorpong/">
        <i class="icon facebook"></i>Schörpong
      </a>
      <a class="item" href="mailto:schorpong@sch.bme.hu">
        <i class="icon mail"></i>schorpong@sch.bme.hu
      </a>
    </div>
    <div class="ui inverted section"></div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div id="offcanvas-nav" uk-offcanvas="overlay: true">
    <div class="uk-offcanvas-bar">

        <ul class="uk-nav uk-nav-default">
            <li><%= link_to 'E-schop',goods_path  %></li>

                <li style="position: relative; left: -6px;">                
            </li>

            <% if current_user.nil? %>
                <li>   <%= link_to 'Bejelentkezés', new_user_session_path %>  </li>
            <% else %>           
                <li class="uk-nav-header">
                    <a href="#"><%= current_user.username %></a>
                </li>
                <li>
                    <%=link_to user_path(current_user.id) do %>
                        Profilom 
                        <% if current_user.roomnumber.nil? %>
                            <span class="uk-badge uk-background-secondary"> ! </span>
                        <% end %>
                    <%end%>
                </li>

                <%@conversations = Conversation.where("sender_id = ? OR receiver_id = ?", current_user.id, current_user.id)%>
                <% message_num = 0 %>
                <% @conversations.each do |conversation| %>
                    <% unless conversation.unread_message_count(current_user).zero? %>
                        <% message_num += 1 %>
                    <% end %>
                <% end %>
                <li>
                    <%=link_to conversations_path(mobile: 'left') do %>
                        Üzenetek <span class="uk-badge"><%=message_num.to_s%></span>
                    <%end%>
                </li>
                <% @purchases = Purchase.all %>
                <% @goods = Good.all %>
                <% cart_num = 0 %>
                <% @purchases.each do |p| %>
                    <% if p.buyer_id == current_user.id%>
                        <% cart_num += 1 %>
                    <% end %>
                <%end%>
                        
                <li>
                    <%=link_to user_my_cart_path do %>
                        Kosaram <span class="uk-badge"><%=cart_num.to_s%></span>
                    <%end%>
                </li> 
                <% good_num = 0 %>
                <% @goods.each do |g| %>
                    <% if g.seller_id == current_user.id %>
                        <% good_num += 1 %>
                    <% end %>
                <%end%>
                <li>
                    <%=link_to  user_my_goods_path do %>
                    Termékeim <span class="uk-badge"><%=good_num.to_s%></span>
                    <%end%>
                </li>
                <% good_num = 0 %>
                <% @purchases.each do |p| %>
                    <% if Good.with_deleted.find_by_id(p.good_id).seller_id == current_user.id %>
                        <% good_num += 1 %>
                    <% end %>
                <%end%>
                        
                <li>
                        <%=link_to user_sold_goods_path do %>
                        Megrendelt termékeim <span class="uk-badge"><%=good_num.to_s%></span>
                        <%end%>
                </li>

                <li><%= link_to 'Új termék felvétele', new_good_path, method: :get %></li> 
                <li><%= link_to 'Kijelentkezés', destroy_user_session_path, method: :delete %></li>                  
            <%end%>
          </ul>
    </div>
</div>

app/views/layouts/_topbar.html.erb
 <script>
  $(document).ready(function(){
  document.documentElement.style.overflowY="auto";
    });
  
  </script>
<div uk-sticky="sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; bottom: #sticky-dropdown" class = "uk-visible@m">
<nav class="uk-navbar-container uk-margin uk-navbar" uk-navbar>

    <div class="uk-navbar-left uk-padding uk-padding-remove-top uk-padding-remove-bottom ">
        <ul class="uk-navbar-nav">
            <li><%= link_to 'E-schop', goods_index_get_path  %></li>
        </ul>
    </div>

    <div class="uk-navbar-center">
        <%unless @index%>
            <ul class="uk-navbar-nav">
                <li>
                    <%= form_tag filter_index_get_path, method: :get, id: "nameform", class: "uk-search uk-search-default" do %>
                        <input name="searched_phrase" id="scearched_prase" class="uk-search-input" type="search" placeholder="Keresés...">
                    <% end %>
                    <button  type="submit" form="nameform" class="uk-search-icon-flip" uk-search-icon></button>
                </li>
            </ul>
        <%end%> 
    </div>

    <div class="uk-navbar-right uk-padding uk-padding-remove-top uk-padding-remove-bottom ">

            <ul class="uk-navbar-nav">
            <% if current_user.nil? %>
                <li><%= link_to 'Bejelentkezés', new_user_session_path %></li> 
            <% else %>
                <li><a href="#" class="uk-visible@m"><%= current_user.username %></a></li>
                <div uk-dropdown="mode: click" class="uk-visible@m" style="z-index: -1;">
                    <ul class="uk-nav uk-dropdown-nav">
                        <li>
                            <%=link_to user_path(current_user.id) do %>
                                Profilom 
                                <% if current_user.roomnumber.nil? %>
                                  <span class="uk-badge uk-background-secondary"> ! </span>
                                <% end %>
                            <%end%>
                        </li>
                        <%@conversations = Conversation.where("sender_id = ? OR receiver_id = ?", current_user.id, current_user.id)%>
                        <% message_num = 0 %>
                        <% @conversations.each do |conversation| %>
                            <% unless conversation.unread_message_count(current_user).zero? %>
                                <% message_num += 1 %>
                            <% end %>
                        <% end %>
                        <li>
                            <%=link_to conversations_path do %>
                                Üzenetek <span class="uk-badge"><%=message_num.to_s%></span>
                            <%end%>
                        </li>
                        <% @purchases = Purchase.all %>
                            <% @goods = Good.all %>
                            <% cart_num = 0 %>
                            <% @purchases.each do |p| %>
                                <% if p.buyer_id == current_user.id%>
                                    <% cart_num += 1 %>
                                <% end %>
                            <%end%>
                            <li>
                                <%=link_to user_my_cart_path do %>
                                    Kosaram <span class="uk-badge"><%=cart_num.to_s%></span>
                                <%end%>
                            </li>
                            <% good_num = 0 %>
                            <% @goods.each do |g| %>
                                <% if g.seller_id == current_user.id %>
                                    <% good_num += 1 %>
                                <% end %>
                            <%end%>
                          
                            <li> 
                                <%=link_to  user_my_goods_path do %>
                                    Termékeim <span class="uk-badge"><%=good_num.to_s%></span>
                                <%end%>
                                </li>
                            <% good_num = 0 %>
                            <% @purchases.each do |p| %>
                                <% if Good.with_deleted.find_by_id(p.good_id).seller_id == current_user.id %>
                                    <% good_num += 1 %>
                                <% end %>
                            <%end%>
                        
                            <li>
                                <%=link_to user_sold_goods_path do %>
                                    Megrendelt termékeim <span class="uk-badge"><%=good_num.to_s%></span>
                                <%end%>
                            </li>
                                <li><%= link_to 'Új termék felvétele', new_good_path, method: :get %></li> 
                            <li><%= link_to 'Kijelentkezés', destroy_user_session_path, method: :delete %></li>
                    </ul>
                </div>
            <%end%>
            </ul>
        <div>  

</nav>
</div>
<div uk-sticky="sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; bottom: #sticky-dropdown" class = "uk-hidden@m">
<nav class="uk-navbar-container uk-margin uk-navbar" uk-navbar>
    <div class="uk-navbar-left">
        <a uk-icon="menu" uk-toggle="target: #offcanvas-nav"  class="uk-navbar-item uk-logo router-link-exact-active uk-active uk-hidden@m uk-padding-remove-right"> </a>
        <a uk-icon="menu" uk-toggle="target: #offcanvas-nav"  class="uk-navbar-item uk-logo router-link-exact-active uk-active uk-invisible uk-padding-remove-right"> </a>
         <%unless @index%>
            <ul class="uk-navbar-nav">
                <li>
                    <%= form_tag filter_index_get_path, method: :get, id: "nameform", class: "uk-search uk-search-default" do %>
                        <input name="searched_phrase" id="scearched_prase" class="uk-search-input" type="search" placeholder="Keresés...">
                    <% end %>
                    <button  type="submit" form="nameform" class="uk-search-icon-flip" uk-search-icon></button>
                </li>
            </ul>
        <%end%> 
    </div>
    <div class="uk-navbar-right">
        <ul class="uk-navbar-nav">
            <li><%= link_to 'E-schop', goods_index_get_path  %></li>
        </ul>
    </div>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="hu">
  <head>
    <title>ESchop</title>
       <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'stylesheets'%>
  </head>
 
  <body>
    <%if @index%>
      <div class = "bg-main-index" id = "bg"></div>
    <% elsif !@conversation_page %>
      <div class = "bg-main" id = "bg"></div>
    <% end %>
    <%=render 'layouts/topbar'%>
    <%=render 'layouts/sidebar'%>
    <% unless notice.nil? %>
      <script>UIkit.notification({message: '<%= notice %>', status: 'success', timeout: 3000})</script>
    <% end %>
    
    <% unless alert.nil? %>
      <script>UIkit.notification({message: '<%= alert %>', status: 'danger', timeout: 3000})</script>
    <% end %>
    <main>
    <%= yield %>    
    </main>
     <%= render 'layouts/footer' %>

  </body>  
  <%= javascript_pack_tag 'application'%>
</html>